package com.myspace.spectrum;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class One_day_before_scheduled_appointment implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public One_day_before_scheduled_appointment() {
    }




}