package com.myspace.spectrum;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Patient implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer age;

	public Patient() {
	}

	public java.lang.Integer getAge() {
		return this.age;
	}

	public void setAge(java.lang.Integer age) {
		this.age = age;
	}

	public Patient(java.lang.Integer age) {
		this.age = age;
	}

}