package com.myspace.spectrum;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Patient_has_appointment_scheduled implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Patient_has_appointment_scheduled() {
    }




}