package com.myspace.spectrum;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Patient_admitted_to_hospital implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Patient_admitted_to_hospital() {
    }




}