package com.myspace.spectrum;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Scheduled_facility_offers_valet implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Scheduled_facility_offers_valet() {
    }




}