package com.myspace.spectrum;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Serve_up_a_cancellation_offer implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Serve_up_a_cancellation_offer() {
    }




}